# Generated by Django 5.0.6 on 2024-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
