# Generated by Django 5.0.6 on 2024-06-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_workrequest_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
