# Generated by Django 5.0.6 on 2024-06-28 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_work_date_work_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='uploads/avatars')),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.TextField()),
                ('pin', models.CharField(max_length=6)),
                ('phone_no', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
