# Generated by Django 5.0.6 on 2024-07-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
